version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432  
      POSTGRES_DB: swen356
      POSTGRES_USER: swen356CIUser
      POSTGRES_PASSWORD: bubbles987

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install Flask Flask-RESTful Flask-CORS

      - run:
          name: Install PostgreSQL
          command: |
            sudo apt-get update
            sudo apt-get install -y postgresql
      
      - run:
          name: Start PostgreSQL Service
          command: |
            sudo service postgresql start
            psql -U postgres -c "CREATE USER swen365CIUser WITH PASSWORD 'bubbles987';"
        
      - run:
            name: Check Python version
            command: python --version

      - run:
          name: Debug database connection
          command: |
            sudo service postgresql status
            echo "Attempting to connect to the database..."
            nc -vz $POSTGRES_HOST $POSTGRES_PORT

      - run:
          name: Start server
          command: |
            python server/server.py &
            sleep 3

      - run:
          name: Run unit tests
          command: python -m unittest -v

      # Optionally, you can use pytest instead of unittest
      # - run:
      #     name: Run unit tests
      #     command: pytest

      # Optionally, you can debug a failure with curl
      # - run:
      #     name: Debug failure
      #     command: curl http://localhost:5000/

  # Define more jobs if needed (e.g., deploy, etc.)

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
