version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    environment:
      POSTGRES_DB: swen356
      POSTGRES_USER: swen356CIUser
      POSTGRES_PASSWORD: bubbles987

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Copy configuration files
          command: cp config/gitlab-credentials.yml config/db.yml

      - run:
          name: Check Python version
          command: python --version

      - run:
          name: Start server
          command: |
            python src/server.py &
            sleep 3

      - run:
          name: Run unit tests
          command: python -m unittest -v

      # Optionally, you can use pytest instead of unittest
      # - run:
      #     name: Run unit tests
      #     command: pytest

      # Optionally, you can debug a failure with curl
      # - run:
      #     name: Debug failure
      #     command: curl http://localhost:5000/

  # Define more jobs if needed (e.g., deploy, etc.)

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
