image:
  name: ritse/swen344db:latest

services:
  
postgres:11

variables:
  POSTGRES_DB: swen344DB
  POSTGRES_USER: swen344CIUser
  POSTGRES_PASSWORD: bubbles9874

before_script:
  
pip install -r requirements.txt
cp config/gitlab-credentials.yml config/db.yml
python --version
python src/server.py & # fire up the server before we run our tests

  
sleep 3

testrunner:
  script:
    
python -m unittest -v # run the unit tests; -v prints the test being run

    # - pytest # optional, use instead of unittest. friendlier output.

    # - curl http://localhost:5000/ # you can also debug a failure with curl

  stage: test
