version: 2.1

jobs:
  build:
    docker:
      - image: bookclub
    working_directory: ~/app
    services:
      - postgres:11
    environment:
      POSTGRES_DB: swen365
      POSTGRES_USER: swen365CIUser
      POSTGRES_PASSWORD: bubbles987

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install -y python3-pip
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            python3 -m unittest -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
