version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: cimg/postgres:13.14

    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432  
      POSTGRES_DB: swen356
      POSTGRES_USER: swen356CIUser
      POSTGRES_PASSWORD: bubbles987

    steps:
      - checkout

      - run:
          name: Install PostgreSQL client
          command: sudo apt-get update && sudo apt-get install -y postgresql-client

      - run:
          name: Initialize Database
          command: |
            psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE ROLE swen356CIUser WITH LOGIN PASSWORD 'bubbles987';"
            psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE DATABASE $POSTGRES_DB;"
            # Add additional commands to create tables, seed data, etc.

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install Flask Flask-RESTful Flask-CORS

      - run:
          name: Check Python version
          command: python --version
          
      - run:
          name: Start server
          command: |
            python server/server.py &
            sleep 3

      - run:
          name: Run unit tests
          command: python -m unittest -v

  # Define more jobs if needed (e.g., deploy, etc.)

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
