version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: cimg/postgres:13.14

    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432  
      POSTGRES_DB: swen356
      POSTGRES_USER: swen356CIUser
      POSTGRES_PASSWORD: bubbles987

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install Flask Flask-RESTful Flask-CORS
      
      - run:
          name: Check Python version
          command: python --version

      - run:
          name: Debug database connection
          command: |
            docker ps  # Check if PostgreSQL container is running
            echo "Attempting to connect to the database..."
            nc -vz $POSTGRES_HOST $POSTGRES_PORT

      - run:
          name: Start server
          command: |
            python server/server.py &
            sleep 3

      - run:
          name: Run unit tests
          command: python -m unittest -v

  # Define more jobs if needed (e.g., deploy, etc.)

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
