version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
           TEST_DATABASE_URL: postgresql://root@localhost/swen356?sslmode=disable
      - image: cimg/postgres:16.2
        environment:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: swen356
          POSTGRES_USER: root
          POSTGRES_PASSWORD: bubbles987

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install Flask Flask-RESTful Flask-CORS

      - run:
          name: Check Python version
          command: python --version

      - run:
          name: Run unit tests
          command: |
            python server/server.py &
            sleep 7 
            ps aux  
            python -m unittest -v

  # Define more jobs if needed (e.g., deploy, etc.)

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
